[package]
name = "lltimer"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = "0.8.4"
fxhash = "0.2.1"
smallvec = { version = "1.13.2", features = ["union", "const_generics"] }
tokio = { version = "1.42.0", features = ["sync", "time"] }
pin-project = "1"
